-- ----------------------------
--  跑批记录表
-- ----------------------------
ALTER TABLE `TB_BATCH_TASK` CHANGE `ID` `ID` varchar(255) NOT NULL COMMENT '跑批记录ID';
ALTER TABLE `TB_BATCH_TASK` CHANGE `TASK_NAME` `TASK_NAME` VARCHAR(32) NOT NULL COMMENT '任务名称';
ALTER TABLE `TB_BATCH_TASK` CHANGE `TASK_STATUS` `TASK_STATUS` VARCHAR(8) NOT NULL COMMENT '任务状态';
ALTER TABLE `TB_BATCH_TASK` CHANGE `TASK_DATE` `TASK_DATE` VARCHAR(8) NOT NULL COMMENT '执行时间';
ALTER TABLE `TB_BATCH_TASK` CHANGE `TIMERECORD` `TIMERECORD` datetime NOT NULL COMMENT '记录时间';
ALTER TABLE `TB_BATCH_TASK` CHANGE `TIMEUPDATE` `TIMEUPDATE` datetime NOT NULL COMMENT '更新时间';

-- ----------------------------
--  每日计息表
-- ----------------------------
ALTER TABLE `TB_DAILY_INTEREST_STATISTICS` CHANGE `ID` `ID` varchar(255) NOT NULL COMMENT '每日计息记录ID';
ALTER TABLE `TB_DAILY_INTEREST_STATISTICS` CHANGE `TIMERECORD` `TIMERECORD` datetime NOT NULL COMMENT '记录时间';
ALTER TABLE `TB_DAILY_INTEREST_STATISTICS` CHANGE `TIMEUPDATE` `TIMEUPDATE` datetime NOT NULL COMMENT '更新时间';
ALTER TABLE `TB_DAILY_INTEREST_STATISTICS` CHANGE `DAILY_INTEREST` `DAILY_INTEREST` decimal(15,2) DEFAULT NULL COMMENT '当日利息或罚息';
ALTER TABLE `TB_DAILY_INTEREST_STATISTICS` CHANGE `LOAN_ID` `LOAN_ID` varchar(255) NOT NULL COMMENT '借款ID';
ALTER TABLE `TB_DAILY_INTEREST_STATISTICS` CHANGE `OVERDUE_INTEREST` `OVERDUE_INTEREST` decimal(15,2) NOT NULL COMMENT '截止到当日的逾期利息';
ALTER TABLE `TB_DAILY_INTEREST_STATISTICS` CHANGE `UNDUE_INTEREST` `UNDUE_INTEREST` decimal(15,2) NOT NULL COMMENT '截止到当日的未还利息';

-- ----------------------------
--  组织机构表
-- ----------------------------
ALTER TABLE `TB_ORGANIZATIONS` CHANGE `ID` `ID` varchar(255) NOT NULL COMMENT '组织机构ID';
ALTER TABLE `TB_ORGANIZATIONS` CHANGE `CREATE_TIME` `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间';
ALTER TABLE `TB_ORGANIZATIONS` CHANGE `ENABLED` `ENABLED` bit(1) DEFAULT NULL COMMENT '是否启用';
ALTER TABLE `TB_ORGANIZATIONS` CHANGE `LOGO` `LOGO` varchar(255) DEFAULT NULL COMMENT '机构LOGO';
ALTER TABLE `TB_ORGANIZATIONS` CHANGE `NOTE` `NOTE` varchar(255) DEFAULT NULL COMMENT '备注';
ALTER TABLE `TB_ORGANIZATIONS` CHANGE `ORGANIZATION_NAME` `ORGANIZATION_NAME` varchar(255) DEFAULT NULL COMMENT '英文名称';
ALTER TABLE `TB_ORGANIZATIONS` CHANGE `ORGANIZATION_NICKNAME` `ORGANIZATION_NICKNAME` varchar(255) DEFAULT NULL COMMENT '中文名称';
ALTER TABLE `TB_ORGANIZATIONS` CHANGE `ORGANIZATION_PATH` `ORGANIZATION_PATH` varchar(255) DEFAULT NULL COMMENT '组织机构路径';
ALTER TABLE `TB_ORGANIZATIONS` CHANGE `PARENT_ORGANIZATION_ID` `PARENT_ORGANIZATION_ID` varchar(255) DEFAULT NULL COMMENT '父级机构ID';

-- ----------------------------
--  权限表
-- ----------------------------
ALTER TABLE `TB_PERMISSIONS` CHANGE `ID` `ID` varchar(255) NOT NULL COMMENT '权限ID';
ALTER TABLE `TB_PERMISSIONS` CHANGE `CREATE_TIME` `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间';
ALTER TABLE `TB_PERMISSIONS` CHANGE `ENABLED` `ENABLED` bit(1) DEFAULT NULL COMMENT '是否启用';
ALTER TABLE `TB_PERMISSIONS` CHANGE `NOTE` `NOTE` varchar(255) DEFAULT NULL COMMENT '备注';
ALTER TABLE `TB_PERMISSIONS` CHANGE `TYPE` `TYPE` INT NULL COMMENT '权限类型';
ALTER TABLE `TB_PERMISSIONS` CHANGE `PERMISSION_NAME` `PERMISSION_NAME` varchar(255) DEFAULT NULL COMMENT '权限名称';
ALTER TABLE `TB_PERMISSIONS` CHANGE `PERMISSION_NICKNAME` `PERMISSION_NICKNAME` varchar(255) DEFAULT NULL COMMENT '中文描述';
ALTER TABLE `TB_PERMISSIONS` CHANGE `PERMISSION_URL` `PERMISSION_URL` varchar(255) DEFAULT NULL COMMENT '权限URL地址';

-- ----------------------------
--  角色表
-- ----------------------------
ALTER TABLE `TB_ROLES` CHANGE `ID` `ID` varchar(255) NOT NULL COMMENT '角色ID';
ALTER TABLE `TB_ROLES` CHANGE `CREATE_TIME` `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间';
ALTER TABLE `TB_ROLES` CHANGE `ENABLED` `ENABLED` bit(1) DEFAULT NULL COMMENT '是否启用';
ALTER TABLE `TB_ROLES` CHANGE `INHERITED` `INHERITED` bit(1) DEFAULT NULL COMMENT '是否继承';
ALTER TABLE `TB_ROLES` CHANGE `NOTE` `NOTE` varchar(255) DEFAULT NULL COMMENT '备注';
ALTER TABLE `TB_ROLES` CHANGE `ROLE_NAME` `ROLE_NAME` varchar(255) DEFAULT NULL COMMENT '角色名称';
ALTER TABLE `TB_ROLES` CHANGE `ROLE_NICKNAME` `ROLE_NICKNAME` varchar(255) DEFAULT NULL COMMENT '角色中文名称';

-- ----------------------------
--  用户表
-- ----------------------------
ALTER TABLE `TB_USERS` CHANGE `ID` `ID` varchar(255) NOT NULL COMMENT '用户ID';
ALTER TABLE `TB_USERS` CHANGE `USER_NAME` `USER_NAME` varchar(255) DEFAULT NULL COMMENT '用户名称';
ALTER TABLE `TB_USERS` CHANGE `PASSWORD` `PASSWORD` varchar(255) DEFAULT NULL COMMENT '用户密码';
ALTER TABLE `TB_USERS` CHANGE `NICKNAME` `NICKNAME` varchar(255) DEFAULT NULL COMMENT '用户昵称';
ALTER TABLE `TB_USERS` CHANGE `EMAIL` `EMAIL` varchar(255) DEFAULT NULL COMMENT '邮件地址';
ALTER TABLE `TB_USERS` CHANGE `ENABLED` `ENABLED` bit(1) DEFAULT NULL COMMENT '启用状态';
ALTER TABLE `TB_USERS` CHANGE `NOTE` `NOTE` varchar(255) DEFAULT NULL COMMENT '备注';
ALTER TABLE `TB_USERS` CHANGE `SALT` `SALT` int(11) DEFAULT NULL COMMENT '参与计算密码hash值的salt';
ALTER TABLE `TB_USERS` CHANGE `PHONE_NUMBER` `PHONE_NUMBER` VARCHAR(32) NULL COMMENT '电话号码';
ALTER TABLE `TB_USERS` CHANGE `TELE_NUMBER` `TELE_NUMBER` varchar(255) DEFAULT NULL COMMENT '电话号码';
ALTER TABLE `TB_USERS` CHANGE `CREATE_TIME` `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间';
ALTER TABLE `TB_USERS` CHANGE `LAST_LOGIN_TIME` `LAST_LOGIN_TIME` DATETIME NULL COMMENT  '上次登录时间';

-- ----------------------------
--  系统设置表
-- ----------------------------
ALTER TABLE `TB_SYSTEM_CONFIG` CHANGE `CONFIG_KEY` `CONFIG_KEY` VARCHAR(255) NOT NULL COMMENT '属性键值';
ALTER TABLE `TB_SYSTEM_CONFIG` CHANGE `CONFIG_VALUE` `CONFIG_VALUE` VARCHAR(255) NOT NULL COMMENT '属性值';

-- ----------------------------
--  统一支付卡bin信息表
-- ----------------------------
ALTER TABLE `TB_UNIPAY_CARDBIN` CHANGE `ID` `ID` varchar(255) NOT NULL COMMENT '统一支付卡bin信息记录ID';
ALTER TABLE `TB_UNIPAY_CARDBIN` CHANGE `CARD_BIN` `CARD_BIN` varchar(255) NOT NULL COMMENT '卡bin';
ALTER TABLE `TB_UNIPAY_CARDBIN` CHANGE `LENGTH` `LENGTH` varchar(255) NOT NULL COMMENT '卡号长度';
ALTER TABLE `TB_UNIPAY_CARDBIN` CHANGE `TYPE` `TYPE` varchar(255) NOT NULL COMMENT '卡种';
ALTER TABLE `TB_UNIPAY_CARDBIN` CHANGE `BANK_NAME` `BANK_NAME` varchar(255) NOT NULL COMMENT '所属银行名称';
ALTER TABLE `TB_UNIPAY_CARDBIN` CHANGE `UNIPAY_BANK_CODE` `UNIPAY_BANK_CODE` varchar(255) NOT NULL COMMENT '统一支付行号';
ALTER TABLE `TB_UNIPAY_CARDBIN` CHANGE `UNIPAY_BANK_NAME` `UNIPAY_BANK_NAME` varchar(255) NOT NULL COMMENT '统一支付行名';
ALTER TABLE `TB_UNIPAY_CARDBIN` CHANGE `TIMERECORD` `TIMERECORD` datetime NOT NULL COMMENT '记录时间';
ALTER TABLE `TB_UNIPAY_CARDBIN` CHANGE `TIMEUPDATE` `TIMEUPDATE` datetime NOT NULL COMMENT '更新时间';

-- ----------------------------
--  TB_BAILOR_DAILY_STATISTICS
-- ----------------------------
ALTER TABLE `TB_BAILOR_DAILY_STATISTICS` CHANGE `ID` `ID` VARCHAR(255) NOT NULL COMMENT '委托机构日常统计ID';
ALTER TABLE `TB_BAILOR_DAILY_STATISTICS` CHANGE `TIMERECORD` `TIMERECORD` DATETIME NOT NULL COMMENT '创建日期';
ALTER TABLE `TB_BAILOR_DAILY_STATISTICS` CHANGE `TIMEUPDATE` `TIMEUPDATE` DATETIME NOT NULL COMMENT '修改日期';
ALTER TABLE `TB_BAILOR_DAILY_STATISTICS` CHANGE `DATE` `DATE` DATETIME NOT NULL COMMENT '统计日期';
ALTER TABLE `TB_BAILOR_DAILY_STATISTICS` CHANGE `REPAY_FEE` `REPAY_FEE` DECIMAL(15,2) NOT NULL COMMENT '当日还款手续费';
ALTER TABLE `TB_BAILOR_DAILY_STATISTICS` CHANGE `REPAY_INTEREST` `REPAY_INTEREST` DECIMAL(15,2) NOT NULL COMMENT '当日还款利息';
ALTER TABLE `TB_BAILOR_DAILY_STATISTICS` CHANGE `REPAY_PENALTY_INTEREST` `REPAY_PENALTY_INTEREST` DECIMAL(15,2) NOT NULL COMMENT '当日还款罚息';
ALTER TABLE `TB_BAILOR_DAILY_STATISTICS` CHANGE `REPAYMENT_PRINCIPAL` `REPAYMENT_PRINCIPAL` DECIMAL(15,2) NOT NULL COMMENT '当日还款本金';
ALTER TABLE `TB_BAILOR_DAILY_STATISTICS` CHANGE `SETTLED_AMOUNT` `SETTLED_AMOUNT` BIGINT(20) NOT NULL COMMENT '当日放款总金额';
ALTER TABLE `TB_BAILOR_DAILY_STATISTICS` CHANGE `BAILOR_ID` `BAILOR_ID` VARCHAR(255) NOT NULL COMMENT '委托机构ID';
-- ----------------------------
--  TB_BAILOR_LOAN_STATISTICS
-- ----------------------------
ALTER TABLE `TB_BAILOR_LOAN_STATISTICS` CHANGE `ID` `ID` VARCHAR(255) NOT NULL COMMENT '委托机构总体统计ID';
ALTER TABLE `TB_BAILOR_LOAN_STATISTICS` CHANGE `TIMERECORD` `TIMERECORD` DATETIME NOT NULL COMMENT '创建日期';
ALTER TABLE `TB_BAILOR_LOAN_STATISTICS` CHANGE `TIMEUPDATE` `TIMEUPDATE` DATETIME NOT NULL COMMENT '修改日期';
ALTER TABLE `TB_BAILOR_LOAN_STATISTICS` CHANGE `CLEARED_COUNT` `CLEARED_COUNT` BIGINT(20) NOT NULL COMMENT '已结清笔数';
ALTER TABLE `TB_BAILOR_LOAN_STATISTICS` CHANGE `LOAN_AMOUNT` `LOAN_AMOUNT` BIGINT(20) NOT NULL COMMENT '贷款总金额';
ALTER TABLE `TB_BAILOR_LOAN_STATISTICS` CHANGE `LOAN_BALANCE` `LOAN_BALANCE` BIGINT(20) NOT NULL COMMENT '贷款余额';
ALTER TABLE `TB_BAILOR_LOAN_STATISTICS` CHANGE `LOAN_COUNT` `LOAN_COUNT` BIGINT(20) NOT NULL COMMENT '贷款总笔数';
ALTER TABLE `TB_BAILOR_LOAN_STATISTICS` CHANGE `OPERATE_DATE` `OPERATE_DATE` DATETIME NOT NULL COMMENT '统计日期';
ALTER TABLE `TB_BAILOR_LOAN_STATISTICS` CHANGE `OVERDUE_COUNT` `OVERDUE_COUNT` BIGINT(20) NOT NULL COMMENT '逾期笔数';
ALTER TABLE `TB_BAILOR_LOAN_STATISTICS` CHANGE `OVERDUE_FEE` `OVERDUE_FEE` DECIMAL(15,2) NOT NULL COMMENT '逾期费用';
ALTER TABLE `TB_BAILOR_LOAN_STATISTICS` CHANGE `OVERDUE_INTEREST` `OVERDUE_INTEREST` DECIMAL(15,2) NOT NULL COMMENT '逾期利息';
ALTER TABLE `TB_BAILOR_LOAN_STATISTICS` CHANGE `OVERDUE_PENALTY_INTEREST` `OVERDUE_PENALTY_INTEREST` DECIMAL(15,2) NOT NULL COMMENT '逾期罚息';
ALTER TABLE `TB_BAILOR_LOAN_STATISTICS` CHANGE `OVERDUE_PRINCIPAL` `OVERDUE_PRINCIPAL` DECIMAL(15,2) NOT NULL COMMENT '逾期本金';
ALTER TABLE `TB_BAILOR_LOAN_STATISTICS` CHANGE `REPAYMENT_FEE` `REPAYMENT_FEE` DECIMAL(15,2) NOT NULL COMMENT '已还费用';
ALTER TABLE `TB_BAILOR_LOAN_STATISTICS` CHANGE `REPAYMENT_INTEREST` `REPAYMENT_INTEREST` DECIMAL(15,2) NOT NULL COMMENT '已还利息';
ALTER TABLE `TB_BAILOR_LOAN_STATISTICS` CHANGE `REPAYMENT_PRINCIPAL` `REPAYMENT_PRINCIPAL` DECIMAL(15,2) NOT NULL COMMENT '已还本金';
ALTER TABLE `TB_BAILOR_LOAN_STATISTICS` CHANGE `RESIDUAL_FEE` `RESIDUAL_FEE` DECIMAL(15,2) NOT NULL COMMENT '待还费用';
ALTER TABLE `TB_BAILOR_LOAN_STATISTICS` CHANGE `RESIDUAL_INTEREST` `RESIDUAL_INTEREST` DECIMAL(15,2) NOT NULL COMMENT '待还利息';
ALTER TABLE `TB_BAILOR_LOAN_STATISTICS` CHANGE `UNCLEARED_COUNT` `UNCLEARED_COUNT` BIGINT(20) NOT NULL COMMENT '未结清笔数';
ALTER TABLE `TB_BAILOR_LOAN_STATISTICS` CHANGE `BAILOR_ID` `BAILOR_ID` VARCHAR(255) NOT NULL COMMENT '委托机构ID';
ALTER TABLE `TB_BAILOR_LOAN_STATISTICS` CHANGE `RESIDUAL_PRINCIPAL` `RESIDUAL_PRINCIPAL` DECIMAL(15,2) NOT NULL COMMENT '待还本金';
-- ----------------------------
--  TB_CUSTOMER_LOAN_STATISTICS
-- ----------------------------
ALTER TABLE `TB_CUSTOMER_LOAN_STATISTICS` CHANGE `ID` `ID` VARCHAR(255) NOT NULL COMMENT '客户总体统计ID';
ALTER TABLE `TB_CUSTOMER_LOAN_STATISTICS` CHANGE `TIMERECORD` `TIMERECORD` DATETIME NOT NULL COMMENT '创建日期';
ALTER TABLE `TB_CUSTOMER_LOAN_STATISTICS` CHANGE `TIMEUPDATE` `TIMEUPDATE` DATETIME NOT NULL COMMENT '修改日期';
ALTER TABLE `TB_CUSTOMER_LOAN_STATISTICS` CHANGE `CLEARED_COUNT` `CLEARED_COUNT` BIGINT(20) NOT NULL COMMENT '已结清笔数';
ALTER TABLE `TB_CUSTOMER_LOAN_STATISTICS` CHANGE `LOAN_AMOUNT` `LOAN_AMOUNT` BIGINT(20) NOT NULL COMMENT '贷款总金额';
ALTER TABLE `TB_CUSTOMER_LOAN_STATISTICS` CHANGE `LOAN_BALANCE` `LOAN_BALANCE` BIGINT(20) NOT NULL COMMENT '贷款余额';
ALTER TABLE `TB_CUSTOMER_LOAN_STATISTICS` CHANGE `LOAN_COUNT` `LOAN_COUNT` BIGINT(20) NOT NULL COMMENT '贷款总笔数';
ALTER TABLE `TB_CUSTOMER_LOAN_STATISTICS` CHANGE `OPERATE_DATE` `OPERATE_DATE` DATETIME NOT NULL COMMENT '统计日期';
ALTER TABLE `TB_CUSTOMER_LOAN_STATISTICS` CHANGE `OVERDUE_COUNT` `OVERDUE_COUNT` BIGINT(20) NOT NULL COMMENT '逾期笔数';
ALTER TABLE `TB_CUSTOMER_LOAN_STATISTICS` CHANGE `OVERDUE_FEE` `OVERDUE_FEE` DECIMAL(15,2) NOT NULL COMMENT '逾期费用';
ALTER TABLE `TB_CUSTOMER_LOAN_STATISTICS` CHANGE `OVERDUE_INTEREST` `OVERDUE_INTEREST` DECIMAL(15,2) NOT NULL COMMENT '逾期利息';
ALTER TABLE `TB_CUSTOMER_LOAN_STATISTICS` CHANGE `OVERDUE_PENALTY_INTEREST` `OVERDUE_PENALTY_INTEREST` DECIMAL(15,2) NOT NULL COMMENT '逾期罚息';
ALTER TABLE `TB_CUSTOMER_LOAN_STATISTICS` CHANGE `OVERDUE_PRINCIPAL` `OVERDUE_PRINCIPAL` DECIMAL(15,2) NOT NULL COMMENT '逾期本金';
ALTER TABLE `TB_CUSTOMER_LOAN_STATISTICS` CHANGE `REPAYMENT_FEE` `REPAYMENT_FEE` DECIMAL(15,2) NOT NULL COMMENT '已还费用';
ALTER TABLE `TB_CUSTOMER_LOAN_STATISTICS` CHANGE `REPAYMENT_INTEREST` `REPAYMENT_INTEREST` DECIMAL(15,2) NOT NULL COMMENT '已还利息';
ALTER TABLE `TB_CUSTOMER_LOAN_STATISTICS` CHANGE `REPAYMENT_PRINCIPAL` `REPAYMENT_PRINCIPAL` DECIMAL(15,2) NOT NULL COMMENT '已还本金';
ALTER TABLE `TB_CUSTOMER_LOAN_STATISTICS` CHANGE `RESIDUAL_FEE` `RESIDUAL_FEE` DECIMAL(15,2) NOT NULL COMMENT '待还费用';
ALTER TABLE `TB_CUSTOMER_LOAN_STATISTICS` CHANGE `RESIDUAL_INTEREST` `RESIDUAL_INTEREST` DECIMAL(15,2) NOT NULL COMMENT '待还利息';
ALTER TABLE `TB_CUSTOMER_LOAN_STATISTICS` CHANGE `UNCLEARED_COUNT` `UNCLEARED_COUNT` BIGINT(20) NOT NULL COMMENT '未结清笔数';
ALTER TABLE `TB_CUSTOMER_LOAN_STATISTICS` CHANGE `CUSTOMER_ID` `CUSTOMER_ID` VARCHAR(255) NOT NULL COMMENT '委贷平台客户ID';
ALTER TABLE `TB_CUSTOMER_LOAN_STATISTICS` CHANGE `RESIDUAL_PRINCIPAL` `RESIDUAL_PRINCIPAL` DECIMAL(15,2) NOT NULL COMMENT '待还本金';
-- ----------------------------
--  TB_LOANAGENCY_DAILY_STATISTICS
-- ----------------------------
ALTER TABLE `TB_LOANAGENCY_DAILY_STATISTICS` CHANGE `ID` `ID` VARCHAR(255) NOT NULL COMMENT '助贷机构日常统计ID';
ALTER TABLE `TB_LOANAGENCY_DAILY_STATISTICS` CHANGE `TIMERECORD` `TIMERECORD` DATETIME NOT NULL COMMENT '创建日期';
ALTER TABLE `TB_LOANAGENCY_DAILY_STATISTICS` CHANGE `TIMEUPDATE` `TIMEUPDATE` DATETIME NOT NULL COMMENT '修改日期';
ALTER TABLE `TB_LOANAGENCY_DAILY_STATISTICS` CHANGE `DATE` `DATE` DATETIME NOT NULL COMMENT '统计日期';
ALTER TABLE `TB_LOANAGENCY_DAILY_STATISTICS` CHANGE `REPAY_FEE` `REPAY_FEE` DECIMAL(15,2) NOT NULL COMMENT '当日还款手续费';
ALTER TABLE `TB_LOANAGENCY_DAILY_STATISTICS` CHANGE `REPAY_INTEREST` `REPAY_INTEREST` DECIMAL(15,2) NOT NULL COMMENT '当日还款利息';
ALTER TABLE `TB_LOANAGENCY_DAILY_STATISTICS` CHANGE `REPAY_PENALTY_INTEREST` `REPAY_PENALTY_INTEREST` DECIMAL(15,2) NOT NULL COMMENT '当日还款罚息';
ALTER TABLE `TB_LOANAGENCY_DAILY_STATISTICS` CHANGE `REPAYMENT_PRINCIPAL` `REPAYMENT_PRINCIPAL` DECIMAL(15,2) NOT NULL COMMENT '当日还款本金';
ALTER TABLE `TB_LOANAGENCY_DAILY_STATISTICS` CHANGE `SETTLED_AMOUNT` `SETTLED_AMOUNT` BIGINT(20) NOT NULL COMMENT '当日放款总金额';
ALTER TABLE `TB_LOANAGENCY_DAILY_STATISTICS` CHANGE `LOAN_AGENCY_ID` `LOAN_AGENCY_ID` VARCHAR(255) NOT NULL COMMENT '助贷机构ID';
-- ----------------------------
--  TB_LOANAGENCY_LOAN_STATISTICS
-- ----------------------------
ALTER TABLE `TB_LOANAGENCY_LOAN_STATISTICS` CHANGE `ID` `ID` VARCHAR(255) NOT NULL COMMENT '助贷机构总体统计ID';
ALTER TABLE `TB_LOANAGENCY_LOAN_STATISTICS` CHANGE `TIMERECORD` `TIMERECORD` DATETIME NOT NULL COMMENT '创建日期';
ALTER TABLE `TB_LOANAGENCY_LOAN_STATISTICS` CHANGE `TIMEUPDATE` `TIMEUPDATE` DATETIME NOT NULL COMMENT '修改日期';
ALTER TABLE `TB_LOANAGENCY_LOAN_STATISTICS` CHANGE `CLEARED_COUNT` `CLEARED_COUNT` BIGINT(20) NOT NULL COMMENT '已结清笔数';
ALTER TABLE `TB_LOANAGENCY_LOAN_STATISTICS` CHANGE `LOAN_AMOUNT` `LOAN_AMOUNT` BIGINT(20) NOT NULL COMMENT '贷款总金额';
ALTER TABLE `TB_LOANAGENCY_LOAN_STATISTICS` CHANGE `LOAN_BALANCE` `LOAN_BALANCE` BIGINT(20) NOT NULL COMMENT '贷款余额';
ALTER TABLE `TB_LOANAGENCY_LOAN_STATISTICS` CHANGE `LOAN_COUNT` `LOAN_COUNT` BIGINT(20) NOT NULL COMMENT '贷款总笔数';
ALTER TABLE `TB_LOANAGENCY_LOAN_STATISTICS` CHANGE `OPERATE_DATE` `OPERATE_DATE` DATETIME NOT NULL COMMENT '统计日期';
ALTER TABLE `TB_LOANAGENCY_LOAN_STATISTICS` CHANGE `OVERDUE_COUNT` `OVERDUE_COUNT` BIGINT(20) NOT NULL COMMENT '逾期笔数';
ALTER TABLE `TB_LOANAGENCY_LOAN_STATISTICS` CHANGE `OVERDUE_FEE` `OVERDUE_FEE` DECIMAL(15,2) NOT NULL COMMENT '逾期费用';
ALTER TABLE `TB_LOANAGENCY_LOAN_STATISTICS` CHANGE `OVERDUE_INTEREST` `OVERDUE_INTEREST` DECIMAL(15,2) NOT NULL COMMENT '逾期利息';
ALTER TABLE `TB_LOANAGENCY_LOAN_STATISTICS` CHANGE `OVERDUE_PENALTY_INTEREST` `OVERDUE_PENALTY_INTEREST` DECIMAL(15,2) NOT NULL COMMENT '逾期罚息';
ALTER TABLE `TB_LOANAGENCY_LOAN_STATISTICS` CHANGE `OVERDUE_PRINCIPAL` `OVERDUE_PRINCIPAL` DECIMAL(15,2) NOT NULL COMMENT '逾期本金';
ALTER TABLE `TB_LOANAGENCY_LOAN_STATISTICS` CHANGE `REPAYMENT_FEE` `REPAYMENT_FEE` DECIMAL(15,2) NOT NULL COMMENT '已还费用';
ALTER TABLE `TB_LOANAGENCY_LOAN_STATISTICS` CHANGE `REPAYMENT_INTEREST` `REPAYMENT_INTEREST` DECIMAL(15,2) NOT NULL COMMENT '已还利息';
ALTER TABLE `TB_LOANAGENCY_LOAN_STATISTICS` CHANGE `REPAYMENT_PRINCIPAL` `REPAYMENT_PRINCIPAL` DECIMAL(15,2) NOT NULL COMMENT '已还本金';
ALTER TABLE `TB_LOANAGENCY_LOAN_STATISTICS` CHANGE `RESIDUAL_FEE` `RESIDUAL_FEE` DECIMAL(15,2) NOT NULL COMMENT '待还费用';
ALTER TABLE `TB_LOANAGENCY_LOAN_STATISTICS` CHANGE `RESIDUAL_INTEREST` `RESIDUAL_INTEREST` DECIMAL(15,2) NOT NULL COMMENT '待还利息';
ALTER TABLE `TB_LOANAGENCY_LOAN_STATISTICS` CHANGE `UNCLEARED_COUNT` `UNCLEARED_COUNT` BIGINT(20) NOT NULL COMMENT '未结清笔数';
ALTER TABLE `TB_LOANAGENCY_LOAN_STATISTICS` CHANGE `LOAN_AGENCY_ID` `LOAN_AGENCY_ID` VARCHAR(255) NOT NULL COMMENT '助贷机构ID';
ALTER TABLE `TB_LOANAGENCY_LOAN_STATISTICS` CHANGE `RESIDUAL_PRINCIPAL` `RESIDUAL_PRINCIPAL` DECIMAL(15,2) NOT NULL COMMENT '待还本金';
-- ----------------------------
--  TB_PRODUCT_DAILY_STATISTICS
-- ----------------------------
ALTER TABLE `TB_PRODUCT_DAILY_STATISTICS` CHANGE `ID` `ID` VARCHAR(255) NOT NULL COMMENT '产品日常统计ID';
ALTER TABLE `TB_PRODUCT_DAILY_STATISTICS` CHANGE `TIMERECORD` `TIMERECORD` DATETIME NOT NULL COMMENT '创建日期';
ALTER TABLE `TB_PRODUCT_DAILY_STATISTICS` CHANGE `TIMEUPDATE` `TIMEUPDATE` DATETIME NOT NULL COMMENT '修改日期';
ALTER TABLE `TB_PRODUCT_DAILY_STATISTICS` CHANGE `BALANCE` `BALANCE` DECIMAL(15,2) NOT NULL COMMENT '当日放款余额';
ALTER TABLE `TB_PRODUCT_DAILY_STATISTICS` CHANGE `DATE` `DATE` DATETIME NOT NULL COMMENT '统计日期';
ALTER TABLE `TB_PRODUCT_DAILY_STATISTICS` CHANGE `PRODUCT_ID` `PRODUCT_ID` VARCHAR(255) NOT NULL COMMENT '产品Id';
ALTER TABLE `TB_PRODUCT_DAILY_STATISTICS` CHANGE `REQUEST_AMOUNT` `REQUEST_AMOUNT` DECIMAL(15,2) NOT NULL COMMENT '当日申请金额';
ALTER TABLE `TB_PRODUCT_DAILY_STATISTICS` CHANGE `REQUEST_COUNT` `REQUEST_COUNT` INT(11) NOT NULL COMMENT '当日申请笔数';
ALTER TABLE `TB_PRODUCT_DAILY_STATISTICS` CHANGE `SETTLED_AMOUNT` `SETTLED_AMOUNT` DECIMAL(15,2) NOT NULL COMMENT '当日放款金额';
ALTER TABLE `TB_PRODUCT_DAILY_STATISTICS` CHANGE `SETTLED_COUNT` `SETTLED_COUNT` INT(11) NOT NULL COMMENT '当日放款笔数';
ALTER TABLE `TB_PRODUCT_DAILY_STATISTICS` CHANGE `REPAY_COUNT` `REPAY_COUNT` INT(11) NOT NULL COMMENT '当日还款笔数';